# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qoe8_XWMt0HCPRLxmDeKs5w1HOroROZW
"""

!pip install openai==0.28.1
import openai

def ask_gpt_about_latex(latex_expression, question, api_key):
    """
    Ask a question about a given LaTeX expression using GPT-3.5 Turbo.

    :param latex_expression: A string containing the LaTeX expression.
    :param question: A string containing the question about the LaTeX expression.
    :param api_key: Your OpenAI API key.
    :return: GPT-3.5's response.
    """
    # Construct the prompt
    prompt = f"LaTeX expression: {latex_expression}\nQuestion: {question}\nAnswer:"

    # Set up OpenAI API
    openai.api_key = api_key

    # Query GPT-3.5 Turbo
    response = openai.Completion.create(
        engine="gpt-3.5-turbo-instruct",
        prompt=prompt,
        max_tokens=100
    )

    return response.choices[0].text.strip()

# Example usage
api_key = "Input Api key "
latex_expression = formatted_formula
question = "whats the equation about?"

answer = ask_gpt_about_latex(latex_expression, question, api_key)
print("GPT-3.5 Turbo says:", answer)